language: node_js
node_js:
    - '6'
before_script:
    - npm install
script:
    - npm run build
after_script:
    - npm run lint
notifications:
    email: false
    slack: nonegroupteam:K9RJ3Ksb5pOrYfc6sRuaWm3Z
